In [104]:
import numpy as np

In [106]:
# 1.Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
a = np.arange(6)
a.dtype

dtype('int32')

In [108]:
#2.	Given a NumPy array 'arr', check if its data type is float64. 
arr = np.array([1.5, 2.6, 3.7])
arr.dtype

dtype('float64')

In [112]:
#3.	Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([3+4j, 2+3j, 4+5j] , dtype = np.complex128)
arr

array([3.+4.j, 2.+3.j, 4.+5.j])

In [116]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.array([1,2,3,4])
arr = arr.astype(np.float32)
arr

array([1., 2., 3., 4.], dtype=float32)

In [118]:
# 5.Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1,2,3,4] , dtype = np.float64)
arr = arr.astype(np.float32)
arr

array([1., 2., 3., 4.], dtype=float32)

In [120]:
#6.Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(arr):
    return arr.shape , arr.size , arr.dtype   
arr = np.array([[1,2,3],[4,5,6]])
array_attributes(arr)

((2, 3), 6, dtype('int32'))

In [122]:
#7.Create a function array_dimension that takes a NumPy array as input and returns its dimensionality. 
def array_dimension(arr):
    return arr.ndim

arr = np.array([1,2,3,4])
array_dimension(arr)

1

In [124]:
#8.Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes
def item_size_info(arr):
    return arr.size , arr.nbytes

arr = np.array([1,2,3,4])
item_size_info(arr)

(4, 16)

In [126]:
#9.Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides

arr = np.array([[1,2,3],[4,5,6]])
array_strides(arr)

(12, 4)

In [128]:
#10.Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1,2,3],[4,5,6]])
shape_stride_relationship(arr)

((2, 3), (12, 4))

In [196]:
#11.Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(arr):
    return np.zeros(arr)

arr = 5
create_zeros_array(5)

In [130]:
#12.Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with 
#ones of size `rows x cols`.
def create_ones_array(arr):
    return np.ones(arr)
create_ones_array([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [132]:
#13.Write a function `generate_range_array` that takes three integers start, stop, and step as arguments 
#and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.
def generate_range_array(start, stop, step):
    arr = np.arange(start, stop, step)
    return arr
arr = generate_range_array(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [134]:
#14.Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and 
#generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
def generate_linear_space(start, stop, num):
    arr = np.linspace(start, stop, num)
    return arr

arr = generate_linear_space(1.0, 10.0, 5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [136]:
#15.Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
    arr = np.eye(n)

arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [138]:
#16.Write a function that takes a Python list and converts it into a NumPy array.
def list_into_array(l):
    return np.array(l)

list_into_array([1,2,3,4])

array([1, 2, 3, 4])

In [140]:
#17.Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
original_arr = np.array([5,6,7,8])
view_arr = original_arr.view()
view_arr[2] = 9
original_arr

array([5, 6, 9, 8])

In [142]:
#18.Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenate_arr(arr1,arr2):
    return np.concatenate((arr1, arr2), axis = 0)

arr1 = np.array([[1,2], [4,5]])
arr2 = np.array([[7,8], [9,0]])
concatenate_arr(arr1,arr2)

array([[1, 2],
       [4, 5],
       [7, 8],
       [9, 0]])

In [146]:
#19.Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.
def concatenate_arr(arr1,arr2):
    return np.concatenate((arr1, arr2), axis = 1)

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8], [9,0]])
concatenate_arr(arr1,arr2)

array([[1, 2, 3, 7, 8],
       [4, 5, 6, 9, 0]])

In [148]:
#20.Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertical_stack(arrays):
    return np.vstack(arrays)

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
vertical_stack([arr1,arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
#21.Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def generate_range_array(start, stop, step):
    		arr = np.arange(start, stop, step)
    		return arr

generate_range_array(1,10,2)

array([1, 3, 5, 7, 9])

In [152]:
#22.Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def array_space(arr):
    arr = np.linspace(0,1,10)
    return arr

array_space(arr)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [154]:
#23.Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def array_space(arr):
    arr = np.logspace(1,1000,5)
    return arr

array_space(arr)

C:\Anaconda\Lib\site-packages\numpy\core\function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

In [156]:
#24.Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import pandas as pd
arr = np.random.randint(1,101, size =(5,3))
pd.DataFrame(arr)

0   1   2
0  74  22   1
1   7  58  10
2  42  34  31
3  95  66  74
4  51  64  82

In [158]:
#25.Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. 
#Use NumPy operations within the Pandas DataFrame.

def replace_values(df,column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df
data = {
   		 'A': [10, -5, 15, -2],
    		 'B': [3, 5, -8, -1]
}
df = pd.DataFrame(data)
replace_values(df,'A')

A  B
0  10  3
1   0  5
2  15 -8
3   0 -1

In [160]:
#26.Access the 3rd element from the given NumPy array. 
arr = np.array([10, 20, 30, 40, 50])
arr[3]

40

In [162]:
#27.Retrieve the element at index (1, 2) from the 2D NumPy array. 
arr_2d = np.array ([[1, 2, 3],
                     [4, 5, 6],
         		     [7, 8, 9]])
arr_2d[1][2]

6

In [164]:
#28.Using boolean indexing, extract elements greater than 5 from the given NumPy array. 
arr = np.array([3, 8, 2, 10, 5, 7])	
arr[arr > 5]

array([ 8, 10,  7])

In [166]:
#29.Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array. 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

In [168]:
#30.Slice the 2D NumPy array to extract the sub-array. `[[2, 3], [5, 6]]` from the given array. 
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
         		   [7, 8, 9]])
arr_2d[0:2, [1,2]]

array([[2, 3],
       [5, 6]])

In [170]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_elements(array, indices):
    extracted_elements = array[indices[:, 0], indices[:, 1]]
    return extracted_elements

array = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]])
indices = np.array([[0, 1],  
                    [1, 2],  
                    [2, 0]])
extract_elements(array, indices)

array([20, 60, 70])

In [172]:
#32.Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
def greater_than_threshold (arr,threshold):
    new_arr = arr[arr > threshold]
    return new_arr

arr = np.array([1,7,8,5,9])
threshold = 6
greater_than_threshold(arr,threshold)

array([7, 8, 9])

In [174]:
#33.Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_elements_3d(array, x_indices, y_indices, z_indices):
    extracted_elements = array[x_indices, y_indices, z_indices]
    return extracted_elements

array = np.array([
    [[10, 20, 30], [40, 50, 60], [70, 80, 90]],
    [[15, 25, 35], [45, 55, 65], [75, 85, 95]],
    [[19, 29, 39], [49, 59, 69], [79, 89, 99]]
]) 
x_indices = np.array([0, 1, 2])  
y_indices = np.array([1, 2, 0])  
z_indices = np.array([2, 1, 0]) 

extract_elements_3d(array, x_indices, y_indices, z_indices)

array([60, 85, 19])

In [176]:
#34.Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def extract_filtered_elements(array, condition1, condition2):
    filtered_elements = array[(array > condition1) & (array < condition2)] 
    return filtered_elements

array = np.array([1,2,3,4,5,6,7,8])
condition1 = 3
condition2 = 8
extract_filtered_elements(array, condition1, condition2)

array([4, 5, 6, 7])

In [178]:
#35.Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract_elements_2d(array, x_indices, y_indices):
    filtered_elements = array[x_indices, y_indices] 
    return filtered_elements

array = np.array([[1,2,3],[4,5,6],[7,8,9]])
x_indices = np.array([0,1,2])
y_indices = np.array([2,1,0])
extract_elements_2d(array, x_indices, y_indices)

array([3, 5, 7])

In [180]:
#36.Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
import random
arr = np.random.randint(1,10, size =(3,3))
arr+5

array([[ 9,  7, 13],
       [ 9, 14, 14],
       [14, 11,  8]])

In [182]:
#37.Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
arr1 = np.random.randint(1,10, size =(1,3))
arr2 = np.random.randint(1,10, size =(3,4))
arr2 * arr1[0][1]

array([[9, 7, 3, 6],
       [9, 7, 6, 4],
       [9, 2, 1, 4]])

In [184]:
#38.Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
arr1 = np.random.randint(1,10, size =(1,4))
arr2 = np.random.randint(1,10, size =(4,3))
new_arr2 = arr2.T
new_arr2+arr1

array([[ 8,  9,  6,  8],
       [ 7,  4,  7,  8],
       [11,  5,  7, 13]])

In [186]:
#39.Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1 = np.random.randint(1,10, size =(3,1))
arr2 = np.random.randint(1,10, size =(1,3))
new_arr2 = arr2.T
arr1+new_arr2

array([[12],
       [14],
       [ 8]])

In [188]:
#40.Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
arr1 = np.random.randint(1,10, size =(2,3))
arr2 = np.random.randint(1,10, size =(2,2))
arr2_expanded = arr2[:, np.newaxis, :]
arr1 * arr2_expanded

ValueError: operands could not be broadcast together with shapes (2,3) (2,1,2) 

In [61]:
#41.Calculate column-wise mean for the given array: 
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.mean(arr, axis=0)

array([2.5, 3.5, 4.5])

In [58]:
#42.Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr, axis=1)

array([3, 6])

In [63]:
#43.For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr, axis=0)

array([4, 5, 6])

In [65]:
#44.For the given array, apply custom function to calculate moving sum along rows. 
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.sum(arr, axis=1)

array([ 6, 15])

In [69]:
#45.In the given array, check if all elements in each column are even. 
arr = np.array([[2, 4, 6], [3, 5, 7]])
np.all(arr % 2 == 0, axis=0)

array([False, False, False])

In [190]:
#46.Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix. 
original_array = np.array([1, 2, 3, 4, 5, 6])
original_array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [192]:
#47.Create a function that takes a matrix as input and returns the flattened array. 
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
def matrix_array(input_matrix):
    return input_matrix.flatten()
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
matrix_array(input_matrix)

array([1, 2, 3, 4, 5, 6])

In [194]:
#48.Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]]) 
array2 = np.array([[5, 6], [7, 8]])
np.concatenate((array1,array2) , axis = 0)
np.concatenate((array1,array2) , axis = 1)
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.expand_dims(original_array, axis = 1)
np.expand_dims(original_array, axis = 0)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [196]:
#49.Create a function that splits an array into multiple sub-arrays along a specified axis. original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
def split_array(array, num_splits, axis=0):
    return np.array_split(array, num_splits, axis=axis)

original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

split_array(original_array, num_splits=3, axis=0)
split_array(original_array, num_splits=3, axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [198]:
#50.Write a function that inserts and then deletes elements from a given array at specified indices. original_array = np.array([1, 2, 3, 4, 5])
#indices_to_insert = [2, 4]
#values_to_insert = [10, 11]
#indices_to_delete = [1, 3]
def insert_del_array(arr, insert_indices,insert_values,del_indices):
    arr = np.insert(arr, insert_indices, insert_values)
    arr = np.delete(arr, del_indices)
    return arr

arr = np.array([1, 2, 3, 4, 5])
insert_indices = [2, 4]
insert_values = [10, 11]
del_indices = [1, 3]
insert_del_array(arr, insert_indices,insert_values,del_indices)

array([ 1, 10,  4, 11,  5])

In [200]:
#51.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
#Perform element-wise addition between `arr1` and `arr2`.
arr1 = np.random.randint(0,10 , size = (1,10))
arr2 = np.arange(1,11)
arr2+arr1

array([[ 2,  7,  4,  7,  8, 10, 15, 17, 14, 15]])

In [202]:
#52.Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. 
#Subtract `arr2` from `arr1` element-wise.
arr1 = np.arange(10,0,-1)
aar2 = np.arange(1,11)
arr2-arr1

array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9])

In [204]:
#53.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
arr1 = np.random.randint(0,10, size = (1,5))
arr2 = np.arange(1,6)
arr1*arr2

array([[ 3,  4, 12,  0, 35]])

In [206]:
#54.Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. 
#Perform element-wise division of `arr1` by `arr2`.
arr1 = np.arange(2,11,2)
arr2 = np.arange(1,6)
arr1/arr2

array([2., 2., 2., 2., 2.])

In [208]:
#55.Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. 
#Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1 = np.arange(1,6)
arr2 = arr1[::-1]
np.power(arr1,arr2)

array([ 1, 16, 27, 16,  5])

In [210]:
#56.Write a function that counts the occurrences of a specific substring within a NumPy array of strings. 
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count_substring_occurrences(arr, substring):
    count = np.char.count(arr, substring).sum()
    return count       

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = ['hello']
count_substring_occurrences(arr, substring)

3

In [212]:
#57.Write a function that extracts uppercase characters from a NumPy array of strings. 
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT']) 

def extract_uppercase(arr):
    uppercase_chars = np.array([''.join([char for char in word if char.isupper()]) for word in arr])
    return uppercase_chars

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT']) 
extract_uppercase(arr)

array(['H', 'W', 'OAI', 'GPT'], dtype='<U3')

In [214]:
#58.Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string. 
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def replace_substring(arr, old_substring, new_substring):
    replaced_arr = np.char.replace(arr, old_substring, new_substring)
    return replaced_arr

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = ['apple']
new_substring = ['orange']
replace_substring(arr, old_substring, new_substring)

array(['orange', 'banana', 'grape', 'pineorange'], dtype='<U10')

In [216]:
#59.Write a function that concatenates strings in a NumPy array element-wise. 
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concatenate_array(arr1,arr2):
    arr3 = np.concatenate((arr1,arr2))
    return arr3
concatenate_array(arr1,arr2)

array(['Hello', 'World', 'Open', 'AI'], dtype='<U5')

In [218]:
#60.Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def find_longest_string_length(arr):
    lengths = np.vectorize(len)(arr)
    max_length = lengths.max()
    return max_length
arr = np.array(['apple', 'banana', 'grape', 'pineapple']) 
find_longest_string_length(arr)

9

In [220]:
#61.Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
arr = np.random.randint(1,1001 , size = (1,100))
np.mean(arr)
np.median(arr)
np.std(arr)
np.var(arr)

78732.41

In [222]:
#62.Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
arr = np.random.randint(1,101 , size = (1,50))
arr_new = np.sort(arr) 
np.percentile(arr, 25) #25th percentile
np.percentile(arr,75) #75th percentile

76.25

In [224]:
#63.Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
arr1 = np.random.randint(1,10 ,size = (2,2))
arr2 = np.random.randint(1,10 ,size = (2,2))
np.corrcoef(arr1,arr2)

array([[ 1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1.],
       [-1., -1.,  1., -1.],
       [ 1.,  1., -1.,  1.]])

In [226]:
#64.Create two matrices and perform matrix multiplication using NumPy's `dot` function.
arr1 = np.random.randint(1,10, size = (3,3))
arr2 = np.random.randint(1,10, size = (3,3))
arr1.dot(arr2)

array([[ 56,  59,  48],
       [104,  86,  86],
       [ 74,  64,  66]])

In [230]:
#65.Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
arr = np.random.randint(10,10001, size = (1,50))
arr_nw = np.sort(arr)
np.percentile(arr_nw ,10)
np.percentile(arr_nw ,50)
np.percentile(arr_nw ,90)
np.percentile(arr_nw , 25)
np.percentile(arr_nw , 75)

6435.0

In [232]:
#66.Create a NumPy array of integers and find the index of a specific element.
arr = np.array([1,2,3,4,5])
np.where(arr == 2)

(array([1], dtype=int64),)

In [238]:
#67.Generate a random NumPy array and sort it in ascending order.
arr = np.random.randint(1,10, size = (1,10))
np.sort(arr)

array([[1, 3, 3, 4, 6, 6, 6, 7, 7, 9]])

In [240]:
#68.Filter elements >20  in the given NumPy array. 
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr > 20]

array([25, 42, 30])

In [242]:
#69.Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
arr[arr%3 == 0]

array([12, 15])

In [244]:
#70.Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array. 
arr = np.array([10, 20, 30, 40, 50])
arr[(arr >= 20) & (arr <= 40)]

array([20, 30, 40])

In [246]:
#71.For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])
arr.dtype.byteorder

'='

In [248]:
#72.For the given NumPy array, perform byte swapping in place using `byteswap()`. 
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap()

array([16777216, 33554432, 50331648])

In [250]:
#73.For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`. 
arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype='>i4')

In [256]:
#74.For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`. 
arr = np.array([1, 2, 3], dtype=np.int32)
arr.dtype.byteorder
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype='>i4')

In [254]:
#75.For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`. 
arr = np.array([1, 2, 3], dtype=np.int32)
arr.dtype.byteorder

'='

In [258]:
#76.Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. 
#Check if modifying `copy_arr` affects `arr1`.
arr1 = np.arange(1,11)
copy_arr = arr1

In [260]:
copy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [262]:
copy_arr[0]

1

In [264]:
copy_arr[2] = 5

In [266]:
copy_arr

array([ 1,  2,  5,  4,  5,  6,  7,  8,  9, 10])

In [268]:
arr1

array([ 1,  2,  5,  4,  5,  6,  7,  8,  9, 10])

In [272]:
#77.Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. 
#Modify an element in `view_slice` and observe if it changes the original `matrix`.
arr1 = np.random.randint(1,10 , size =(3,3))
view_slice = arr1[0:2 , 1:3]
view_slice[0, 0] = 99
arr1

array([[ 6, 99,  6],
       [ 8,  8,  5],
       [ 1,  9,  1]])

In [274]:
#78.Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` 
#and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
array_a = np.random.randint(1,12 , size = (4,3))
view_b = array_a[0:2,0:2]
view_b +=5
array_a

array([[ 6, 12,  6],
       [12,  9,  9],
       [ 9,  4,  3],
       [ 2, 11,  5]])

In [278]:
#79.Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. 
#Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
orig_array = np.random.randint(1,8, size = (2,4))
reshaped_view = np.reshape(orig_array , (4,2))
reshaped_view[2][1] = 9

In [280]:
reshaped_view

array([[5, 2],
       [2, 5],
       [4, 9],
       [5, 7]])

In [282]:
reshaped_view[2][1] = 9

In [284]:
reshaped_view

array([[5, 2],
       [2, 5],
       [4, 9],
       [5, 7]])

In [286]:
orig_array

array([[5, 2, 2, 5],
       [4, 9, 5, 7]])

In [486]:
#80.Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. 
#Modify an element in `data_copy` and verify if it affects the original `data`.
data = np.random.randint(1,10, size = (3,4))

In [488]:
data

array([[3, 6, 9, 7],
       [5, 7, 5, 2],
       [9, 8, 9, 4]])

In [490]:
data_copy = data[data>5]

In [492]:
data_copy

array([6, 9, 7, 7, 9, 8, 9])

In [494]:
data_copy[1] = 8

In [496]:
data_copy

array([6, 8, 7, 7, 9, 8, 9])

In [498]:
data

array([[3, 6, 9, 7],
       [5, 7, 5, 2],
       [9, 8, 9, 4]])

In [500]:
#81.Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
arr_A = np.random.randint(1,10, size = (3,3))

In [502]:
arr_B = np.random.randint(1,10, size = (3,3))

In [504]:
arr_A

array([[5, 7, 4],
       [8, 5, 4],
       [1, 3, 7]])

In [506]:
arr_B

array([[6, 9, 1],
       [4, 2, 3],
       [6, 9, 5]])

In [508]:
arr_A+arr_B

array([[11, 16,  5],
       [12,  7,  7],
       [ 7, 12, 12]])

In [510]:
arr_A-arr_B

array([[-1, -2,  3],
       [ 4,  3,  1],
       [-5, -6,  2]])

In [512]:
#82.Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication
C = np.random.randint(1,10, size = (3,2))
D = np.random.randint(1,10, size = (2,4))

In [516]:
C

array([[9, 6],
       [7, 2],
       [7, 3]])

In [518]:
D

array([[2, 2, 3, 9],
       [3, 2, 3, 5]])

In [524]:
C.dot(D)

array([[ 36,  30,  45, 111],
       [ 20,  18,  27,  73],
       [ 23,  20,  30,  78]])

In [526]:
#83.Create a matrix `E` and find its transpose. 
E = np.random.randint(1,10, size = (3,3))

In [530]:
E

array([[3, 4, 8],
       [2, 8, 5],
       [2, 4, 9]])

In [532]:
E.T

array([[3, 2, 2],
       [4, 8, 4],
       [8, 5, 9]])

In [534]:
#84.Generate a square matrix `F` and compute its determinant.
F = np.random.randint(1,10, size = (3,3))

In [536]:
F

array([[8, 7, 9],
       [3, 8, 8],
       [4, 8, 9]])

In [542]:
np.linalg.det(F)

26.99999999999998

In [544]:
#85.Create a square matrix `G` and find its inverse
G = np.random.randint(1,10, size = (3,3))

In [546]:
G

array([[8, 6, 9],
       [3, 4, 2],
       [8, 3, 9]])

In [548]:
np.linalg.inv(G)

array([[-0.90909091,  0.81818182,  0.72727273],
       [ 0.33333333, -0.        , -0.33333333],
       [ 0.6969697 , -0.72727273, -0.42424242]])